from pathlib import Path

TESTS_FOLDER = Path(__file__).parent
GENERATED_FOLDER = TESTS_FOLDER / "generated"
INPUT_FOLDER = TESTS_FOLDER / "input_files"

INIT_PROJECT_INPUT_FOLDER = INPUT_FOLDER / "init_project"
GENERATED_PROJECT_FOLDER = GENERATED_FOLDER / "init_project"

SOURCES_PROJECT_INPUT_FOLDER = INPUT_FOLDER / "sources_project"

INPUT_PLBUILD_FOLDER = SOURCES_PROJECT_INPUT_FOLDER / "plbuild"
GENERATED_PLBUILD_FOLDER = GENERATED_PROJECT_FOLDER / "plbuild"

INPUT_SOURCES_FOLDER = INPUT_PLBUILD_FOLDER / "sources"
GENERATED_SOURCES_FOLDER = GENERATED_PLBUILD_FOLDER / "sources"

INPUT_DOCUMENT_FOLDER = INPUT_SOURCES_FOLDER / "document"
GENERATED_DOCUMENT_FOLDER = GENERATED_SOURCES_FOLDER / "document"

INPUT_PRESENTATION_FOLDER = INPUT_SOURCES_FOLDER / "presentation"
GENERATED_PRESENTATION_FOLDER = GENERATED_SOURCES_FOLDER / "presentation"